# Generated by Django 5.2.4 on 2025-07-07 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_profile_experience_profile_github_profile_resume_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='posted_on',
            new_name='posted_at',
        ),
        migrations.AlterField(
            model_name='job',
            name='category',
            field=models.CharField(choices=[('Website', 'Website'), ('App', 'App'), ('Tutoring', 'Tutoring')], max_length=100),
        ),
        migrations.AlterField(
            model_name='job',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='profile',
            name='experience',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='resume',
            field=models.FileField(default='default.pdf', upload_to='resumes/'),
            preserve_default=False,
        ),
    ]
