# Generated by Django 5.2.4 on 2025-07-08 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_message_file_message_room_name_alter_message_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='room_name',
            field=models.CharField(max_length=255),
        ),
    ]
