# Generated by Django 5.2.4 on 2025-07-08 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_message_seen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='room_name',
            field=models.CharField(max_length=100),
        ),
    ]
